Repository theforeman/hammer-cli-foreman, pull requests merged in 2018-04, with the labels that each got.

#364 Fixes #23108 - fix logging by requiring logger
  lib/hammer_cli_foreman/logger.rb
Labels: Needs testing, Not yet reviewed

#365 Fixes #23219 - API doc updated to latest upstream (almost 1.18)
  lib/hammer_cli_foreman/image.rb
  test/data/1.18/foreman_api.json
  test/test_helper.rb
  test/unit/helpers/command.rb
  test/unit/host_test.rb
Labels: Ready for merge

#363 Add link a to list of easy bugs into the README
  README.md
Labels: Needs testing, Not yet reviewed

#343 Fixes #19651 - Listing all auth sources
  lib/hammer_cli_foreman/auth_source.rb
  test/functional/auth_source_test.rb
Labels: Demo worthy, Needs re-review, Needs testing
