Repository theforeman/hammer-cli-foreman, pull requests merged in 2018-03, with the labels that each got.

#355 Fixes #22658 - Puppetrun command is moved from hosts to puppet hosts
  lib/hammer_cli_foreman/host.rb
Labels: Ready for merge

#356 Fixes #22718 - raise error when wrong number of ids is resolved
  lib/hammer_cli_foreman/id_resolver.rb
  test/unit/id_resolver_test.rb
Labels: Ready for merge

#357 Fixes #22751 - temporary fix for override values
  lib/hammer_cli_foreman/smart_class_parameter.rb
  lib/hammer_cli_foreman/smart_variable.rb
  lib/hammer_cli_foreman/testing/api_expectations.rb
  test/functional/smart_class_parameter_test.rb
Labels: Needs testing, Not yet reviewed

#358 Fixes #22866 - Pull in the latest strings from Dev
  locale/hammer-cli-foreman.pot
Labels: Needs testing, Not yet reviewed

#360 Fixes #22964 - some numeric options are no longer recognized as numeric
  test/functional/hostgroup/create_test.rb
  test/functional/hostgroup/update_test.rb
Labels: Needs testing, Not yet reviewed

#359 Fixes #4609 - improve class import output
  lib/hammer_cli_foreman/smart_proxy.rb
  test/functional/proxy_test.rb
Labels: Demo worthy, Waiting on contributor

#362 Fixes #22989 - Update to API doc from 1.17
  test/data/1.17/foreman_api.json
  test/test_helper.rb
Labels: Needs re-review, Needs testing

#350 Fixes #21514 - Add personal access token cli support
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/logger.rb
  lib/hammer_cli_foreman/personal_access_token.rb
  lib/hammer_cli_foreman/user.rb
  test/functional/personal_access_token_test.rb
Labels: Demo worthy, Ready for merge
