Repository theforeman/hammer-cli-foreman, pull requests merged in 2018-09, with the labels that each got.

#368 Fixes #20725 - retain data while host update in hammer
  lib/hammer_cli_foreman/hosts/common_update_options.rb
  test/functional/host_test.rb
Labels: Needs testing

#383 Fixes #24748 - Add Cluster option to Hammer CR.
  lib/hammer_cli_foreman/compute_resource.rb
  test/unit/apipie_resource_mock.rb
  test/unit/compute_resource_test.rb
Labels: Needs testing

#385 Fixes #20187 - Display Host Status in Hammer
  lib/hammer_cli_foreman/host.rb
  test/unit/host_test.rb
Labels: Demo worthy

#387 Correct homepage and license in the gemspec
  hammer_cli_foreman.gemspec
Labels: Needs testing, Not yet reviewed

#390 Fixes #24980 - enable structured formatters for refernces.
  lib/hammer_cli_foreman/output/fields.rb
  lib/hammer_cli_foreman/output/formatters.rb
  test/unit/output/formatters_test.rb
Labels: Needs testing
