Repository theforeman/hammer-cli-foreman, pull requests merged in 2018-02, with the labels that each got.

#354 Fixes #22552 - generate --provision-method from apidoc
  lib/hammer_cli_foreman/hosts/common_update_options.rb
Labels: Needs testing, Not yet reviewed

#353 Refs #22517 - Do not resolve already resolved id params
  lib/hammer_cli_foreman/option_sources/id_params.rb
  lib/hammer_cli_foreman/option_sources/ids_params.rb
  test/unit/option_sources/id_params_test.rb
  test/unit/option_sources/ids_params_test.rb
Labels: Needs re-review, Needs testing

#336 Fixes #18636 - Remove deprecation warning from --root-password in host create/update
  doc/host_create.md
  lib/hammer_cli_foreman/hosts/common_update_options.rb
Labels: Needs testing

#351 Fixes #16423 - Hammer should provide commands for showing host's ENC YAML
  lib/hammer_cli_foreman/host.rb
  test/functional/host_test.rb
Labels: Demo worthy, Needs testing
