Repository theforeman/hammer-cli-foreman, pull requests merged in 2019-02, with the labels that each got.

#406 fixes #25964 Hammer host update and set-parameters need clarification
  lib/hammer_cli_foreman/host.rb
  lib/hammer_cli_foreman/hosts/common_update_options.rb
Labels: Needs testing, Not yet reviewed

#408 Fixes #26019 - display uptime
  lib/hammer_cli_foreman/host.rb
Labels: Demo worthy

#398 BZ #20538 - add compute profile commands
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/compute_attribute.rb
  lib/hammer_cli_foreman/compute_profile.rb
  lib/hammer_cli_foreman/compute_resource/base.rb
  lib/hammer_cli_foreman/compute_resource/ec2.rb
  lib/hammer_cli_foreman/compute_resource/gce.rb
  lib/hammer_cli_foreman/compute_resource/help_utils.rb
  lib/hammer_cli_foreman/compute_resource/libvirt.rb
  lib/hammer_cli_foreman/compute_resource/openstack.rb
  lib/hammer_cli_foreman/compute_resource/ovirt.rb
  lib/hammer_cli_foreman/compute_resource/rackspace.rb
  lib/hammer_cli_foreman/compute_resource/register_compute_resources.rb
  lib/hammer_cli_foreman/compute_resource/vmware.rb
  lib/hammer_cli_foreman/compute_resources/all.rb
  lib/hammer_cli_foreman/compute_resources/ec2.rb
  lib/hammer_cli_foreman/compute_resources/ec2/host_help_extenstion.rb
  lib/hammer_cli_foreman/compute_resources/gce.rb
  lib/hammer_cli_foreman/compute_resources/gce/host_help_extenstion.rb
  lib/hammer_cli_foreman/compute_resources/libvirt.rb
  lib/hammer_cli_foreman/compute_resources/libvirt/host_help_extenstion.rb
  lib/hammer_cli_foreman/compute_resources/openstack.rb
  lib/hammer_cli_foreman/compute_resources/openstack/host_help_extenstion.rb
  lib/hammer_cli_foreman/compute_resources/ovirt.rb
  lib/hammer_cli_foreman/compute_resources/ovirt/host_help_extenstion.rb
  lib/hammer_cli_foreman/compute_resources/rackspace.rb
  lib/hammer_cli_foreman/compute_resources/rackspace/host_help_extenstion.rb
  lib/hammer_cli_foreman/compute_resources/vmware.rb
  lib/hammer_cli_foreman/compute_resources/vmware/host_help_extenstion.rb
  lib/hammer_cli_foreman/host.rb
  lib/hammer_cli_foreman/hosts/common_update_help.rb
  lib/hammer_cli_foreman/id_resolver.rb
  lib/hammer_cli_foreman/references.rb
  test/functional/compute_attribute_test.rb
  test/functional/compute_profile_test.rb
Labels: Demo worthy, Needs testing
