Repository theforeman/hammer-cli-foreman, pull requests merged in 2019-11, with the labels that each got.

#450 Refs #27868 - Fix method typo
  lib/hammer_cli_foreman/hosts/common_update_options.rb
  test/functional/host_test.rb
Labels: Needs testing

#443 Refs #27595 - Better prompts for missing arguments
  test/functional/host_test.rb
  test/functional/role_test.rb
  test/functional/template_test.rb
Labels: Needs testing, Waiting on contributor

#451 Refs #28149 - Add release documentation
  .gitignore
  rel-eng/README.md
  rel-eng/gem_release.ipynb
Labels: Needs testing

#442 Refs #17819 - Allow adapters print page by page
  lib/hammer_cli_foreman/commands.rb
  test/unit/test_output_adapter.rb
Labels: Needs testing, Not yet reviewed

#452 Fixes #28318 - Allow login in tty-less execution
  lib/hammer_cli_foreman/auth.rb
  lib/hammer_cli_foreman/authenticate/login.rb
Labels: Needs testing

#453 Fixes #28196 - handle error when empty parameters passed
  lib/hammer_cli_foreman/api/oauth/password_grant.rb
Labels: Needs testing

#455 Fixes #28135 - GCE CR info shows zone field
  lib/hammer_cli_foreman/compute_resource/gce.rb
Labels: Needs testing, Waiting on contributor

#454 Fixes #28176 - Add http-proxy to hammer
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/http_proxy.rb
  test/functional/http_proxy_test.rb
Labels: Needs testing

#456 Fixes #28196 - handle empty params for codegrant flow
  lib/hammer_cli_foreman/api/oauth/authentication_code_grant.rb
Labels: Needs testing

#457 Fixes #28132 - Add images uuid to CR images
  lib/hammer_cli_foreman/compute_resource.rb
  test/functional/compute_resource_test.rb
Labels: Needs testing
