Repository theforeman/hammer-cli-foreman, pull requests merged in 2020-02, with the labels that each got.

#490 Fixes #28899 - Host update doesn't delete assigned puppet classes
  lib/hammer_cli_foreman/hostgroup.rb
  lib/hammer_cli_foreman/hosts/common_update_options.rb
  lib/hammer_cli_foreman/id_resolver.rb
  test/functional/host_test.rb
Labels: Waiting on contributor

#491 Bump hammer version 2.0 develop
  lib/hammer_cli_foreman/version.rb
Labels: Needs testing

#488 Fixes #12471 - add command for managing trends
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/trend.rb
  test/functional/trend_test.rb
  test/unit/apipie_resource_mock.rb
Labels: Needs testing

#484 Fixes #19999 - support associating multiple provisioning templates
  lib/hammer_cli_foreman/associating_commands.rb
  lib/hammer_cli_foreman/commands.rb
  test/functional/associating_commands_test.rb
Labels: Needs testing

#493 Bump version to 2.0.0
  lib/hammer_cli_foreman/version.rb
Labels: Needs testing

#487 Refs #28793 - Better promts for missing arguments
  test/functional/host_test.rb
  test/functional/role_test.rb
  test/functional/template_test.rb
Labels: Needs testing, Not yet reviewed

#495 Fixes tests
  test/functional/associating_commands_test.rb
Labels: Needs testing

#494 Fixes #28869 - change the description of the scoped loc and org
  lib/hammer_cli_foreman/id_resolver.rb
  lib/hammer_cli_foreman/option_builders.rb
Labels: Needs testing

#500 Fixes #29026 - Fix help for ovirt boolean values
  lib/hammer_cli_foreman/compute_resource/ovirt.rb
Labels: Needs testing

#498 Fixes #22573 - Deprecate --root-pass in host group
  lib/hammer_cli_foreman/hostgroup.rb
Labels: Needs re-review, Needs testing

#503 Fixes #29096 - Remove duplicate API requests on AddAssociatedCommand
  lib/hammer_cli_foreman/commands.rb
Labels: Needs testing, Not yet reviewed

#501 Fixes #11279 - Fixed updating host owner when ownertype is Usergroup
  lib/hammer_cli_foreman/hosts/common_update_options.rb
  test/functional/host_test.rb
Labels: Needs re-review, Needs testing

#504 [CP] Cherry picks for 2.0.1
  lib/hammer_cli_foreman/commands.rb
Labels: Needs testing, Not yet reviewed
