Repository theforeman/hammer-cli-foreman, pull requests merged in 2020-01, with the labels that each got.

#472 Refs #28601 - skip one test on Ruby 2.7
  test/functional/http_proxy_test.rb
Labels: Needs testing, Not yet reviewed

#470 Fixes #28472 - add organizations and locations http-proxy info command
  lib/hammer_cli_foreman/http_proxy.rb
Labels: Needs testing

#479 Fixes #28196 - fix undefined method on wrong oidc token endpoint
  lib/hammer_cli_foreman/openid_connect.rb
Labels: Needs testing

#476 Unpin mocha version & fix deprecation warning
  Gemfile
  test/test_helper.rb
Labels: Needs testing

#475 Fixes #28628 - add specific oidc option information
  lib/hammer_cli_foreman/auth.rb
Labels: Needs testing

#478 Fixes #28646 - fix unauthorized user error message
  lib/hammer_cli_foreman/api/session_authenticator_wrapper.rb
  test/unit/api/session_authenticator_wrapper_test.rb
Labels: Needs testing

#480 Fixes #28704 - add auth source external command
  lib/hammer_cli_foreman/auth_source.rb
  lib/hammer_cli_foreman/auth_source_external.rb
  test/unit/apipie_resource_mock.rb
  test/unit/auth_source_external.rb
Labels: Needs testing, Waiting on contributor

#482 [CP-0.19]Fixes #28132 - Add images uuid to CR images (#457)
  lib/hammer_cli_foreman/compute_resource.rb
  test/functional/compute_resource_test.rb
Labels: Needs testing, Not yet reviewed

#481 Refs #28135 - Remove URL field from GCE info (#466)
  lib/hammer_cli_foreman/compute_resource.rb
  lib/hammer_cli_foreman/compute_resource/base.rb
  lib/hammer_cli_foreman/compute_resource/ec2.rb
  lib/hammer_cli_foreman/compute_resource/openstack.rb
  lib/hammer_cli_foreman/compute_resource/ovirt.rb
  lib/hammer_cli_foreman/compute_resource/rackspace.rb
  lib/hammer_cli_foreman/compute_resource/vmware.rb
Labels: Needs testing, Not yet reviewed

#473 Fixes #28599 - drop smart variable handling
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/host.rb
  lib/hammer_cli_foreman/hostgroup.rb
  lib/hammer_cli_foreman/id_resolver.rb
  lib/hammer_cli_foreman/puppet_class.rb
  lib/hammer_cli_foreman/smart_class_parameter.rb
  lib/hammer_cli_foreman/smart_variable.rb
  test/functional/smart_variable_test.rb
  test/unit/host_test.rb
  test/unit/hostgroup_test.rb
  test/unit/puppet_class_test.rb
  test/unit/smart_variable_test.rb
Labels: Needs testing

#485 Fixes #28747 - remove deprecated permissions api parameters
  test/data/2.0/foreman_api.json
  test/data/2.0/v2.en.json
  test/test_helper.rb
  test/unit/filter_test.rb
Labels: Needs re-review, Needs testing

#471 Fixes #28541 - Fix host creation from image and hostgroup
  lib/hammer_cli_foreman/compute_resource/utils.rb
  lib/hammer_cli_foreman/hosts/common_update_options.rb
  test/functional/host_test.rb
Labels: Needs testing

#486 Fixes #28765 - Fix help for filter create command
  lib/hammer_cli_foreman/filter.rb
Labels: Needs re-review, Needs testing
