Repository theforeman/hammer-cli-foreman, pull requests merged in 2020-09, with the labels that each got.

#539 Fixes #30134 - Drop trends from hammer-cli-foreman (#535)
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/trend.rb
  test/functional/trend_test.rb
Labels: Needs testing

#540 Fixes #30794 - Added missing tests to organization test
  test/functional/organization_test.rb
Labels: Needs testing, Not yet reviewed

#542 Fixes #30829 - added missing tests to location test
  test/functional/location_test.rb
Labels: Needs testing, Not yet reviewed

#541 Fixes #30805 - added missing tests to installation medium test
  test/functional/media_test.rb
Labels: Needs re-review, Needs testing

#543 Fixes #30886 - added missing tests to setting
  lib/hammer_cli_foreman/settings.rb
  test/functional/settings_test.rb
Labels: Needs testing, Not yet reviewed
