Repository theforeman/hammer-cli-foreman, pull requests merged in 2020-05, with the labels that each got.

#499 Fixes #28760 - Possibility to create IPv6 subnet
  lib/hammer_cli_foreman/command_extensions.rb
  lib/hammer_cli_foreman/command_extensions/subnet.rb
  lib/hammer_cli_foreman/option_sources.rb
  lib/hammer_cli_foreman/option_sources/referenced_resource_id_params.rb
  lib/hammer_cli_foreman/subnet.rb
  test/functional/subnet/create_test.rb
Labels: Needs testing

#518 i18n - extracting new, pulling from tx
  locale/ca/LC_MESSAGES/hammer-cli-foreman.mo
  locale/ca/hammer-cli-foreman.po
  locale/de/LC_MESSAGES/hammer-cli-foreman.mo
  locale/de/hammer-cli-foreman.po
  locale/en/LC_MESSAGES/hammer-cli-foreman.mo
  locale/en/hammer-cli-foreman.po
  locale/en_GB/LC_MESSAGES/hammer-cli-foreman.mo
  locale/en_GB/hammer-cli-foreman.po
  locale/es/LC_MESSAGES/hammer-cli-foreman.mo
  locale/es/hammer-cli-foreman.po
  locale/fr/LC_MESSAGES/hammer-cli-foreman.mo
  locale/fr/hammer-cli-foreman.po
  locale/hammer-cli-foreman.pot
  locale/it/LC_MESSAGES/hammer-cli-foreman.mo
  locale/it/hammer-cli-foreman.po
  locale/ja/LC_MESSAGES/hammer-cli-foreman.mo
  locale/ja/hammer-cli-foreman.po
  locale/ko/LC_MESSAGES/hammer-cli-foreman.mo
  locale/ko/hammer-cli-foreman.po
  locale/pt_BR/LC_MESSAGES/hammer-cli-foreman.mo
  locale/pt_BR/hammer-cli-foreman.po
  locale/ru/LC_MESSAGES/hammer-cli-foreman.mo
  locale/ru/hammer-cli-foreman.po
  locale/zh_CN/LC_MESSAGES/hammer-cli-foreman.mo
  locale/zh_CN/hammer-cli-foreman.po
  locale/zh_TW/LC_MESSAGES/hammer-cli-foreman.mo
  locale/zh_TW/hammer-cli-foreman.po
Labels: Needs testing, Not yet reviewed

#517 Fixes #29635 - Ask for oauth code only when needed
  lib/hammer_cli_foreman/api/oauth/authentication_code_grant.rb
  lib/hammer_cli_foreman/auth.rb
Labels: Needs testing

#519 Bump hammer_cli to 2.1.0
  hammer_cli_foreman.gemspec
Labels: Needs testing, Not yet reviewed

#513 Fixes #7665 - added manage command to user mail notifications
  lib/hammer_cli_foreman/user.rb
  lib/hammer_cli_foreman/user_mail_notification.rb
  test/data/2.1/foreman_api.json
  test/functional/user_mail_notification_test.rb
Labels: Needs testing

#497 fixes #28973 - Add disable option for user
  lib/hammer_cli_foreman/user.rb
Labels: Blocked by another PR, Needs testing

#521 Fixes #29876 - eliminate auth_type from sessions file
  lib/hammer_cli_foreman/api/connection.rb
  lib/hammer_cli_foreman/api/session_authenticator_wrapper.rb
  lib/hammer_cli_foreman/sessions.rb
  test/unit/sessions_test.rb
Labels: Needs testing

#520 Revert "Refs #28601 - skip one test on Ruby 2.7"
  test/functional/http_proxy_test.rb
Labels: Needs testing
