Repository theforeman/hammer-cli-foreman, pull requests merged in 2020-04, with the labels that each got.

#511 Add rake task with plugin template
  Rakefile
  doc/developer_docs.md
  doc/plugin.md
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/task_helper.rb
Labels: Needs re-review, Needs testing

#514 Fixes #29140 - Add CR to Hostgroup Info
  lib/hammer_cli_foreman/hostgroup.rb
Labels: Needs testing

#489 Refs #28440 - Help contains squeezed options
  lib/hammer_cli_foreman/command_extensions.rb
  lib/hammer_cli_foreman/command_extensions/puppet_environment.rb
  lib/hammer_cli_foreman/command_extensions/puppet_environments.rb
  lib/hammer_cli_foreman/command_extensions/user.rb
  lib/hammer_cli_foreman/hosts/common_update_options.rb
  lib/hammer_cli_foreman/id_resolver.rb
  lib/hammer_cli_foreman/option_builders.rb
  lib/hammer_cli_foreman/subnet.rb
  lib/hammer_cli_foreman/user.rb
  test/functional/template_test.rb
Labels: Needs testing, Not yet reviewed

#512 Refs #29413 - Add aliases for info/list/delete commands
  lib/hammer_cli_foreman/commands.rb
Labels: Needs testing, Not yet reviewed

#510 Fixes #12845 - add the ability to manage bookmarks
  lib/hammer_cli_foreman.rb
  lib/hammer_cli_foreman/bookmark.rb
  test/functional/bookmark_test.rb
Labels: Needs testing
