Repository theforeman/hammer-cli-foreman, pull requests merged in 2021-08, with the labels that each got.

#579 Fixes #32878 - Add parent title option for hostgroup
  lib/hammer_cli_foreman/hostgroup.rb
  test/functional/hostgroup/create_test.rb
  test/functional/hostgroup/update_test.rb
Labels: Needs testing, Not yet reviewed

#577 Fixes #33047- Associate a VM via hammer to a compute resource
  lib/hammer_cli_foreman/compute_resource.rb
Labels: Needs testing, Not yet reviewed, Blocked by another PR

#572 Fixes #19510 - Add proxy status and version to info command
  lib/hammer_cli_foreman/smart_proxy.rb
Labels: Needs testing, Needs re-review

#581 Refs #19510 - Show status once for proxy info
  lib/hammer_cli_foreman/smart_proxy.rb
Labels: Needs testing
